SUPABASE_URL = ""
SUPABASE_KEY = ""

N8N_GEN_URL = "https://virshi.app.n8n.cloud/webhook/webhook/generate-prompts"
N8N_ANALYZE_URL = "https://virshi.app.n8n.cloud/webhook/webhook/analyze"
N8N_RECO_URL = "https://virshi.app.n8n.cloud/webhook/webhook/generate-recos"
N8N_CHAT_WEBHOOK = "https://virshi.app.n8n.cloud/webhook/webhook/chat-bot" 
